### ISSUE TITLE
Wooden Water Bucket Places Still Water

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#100]
Wooden water bucket places still water.

**Comment by valsnoisytoys** [comment]
I can confirm it doing this in 0.1.5.0 as well.  Note that using 3 buckets of water in the following configuration will succeed in giving you a) a water source, and b) flowing water.

xx
x

you get 

aa
aa

and can have b (flowing water) from any of the edges of the infinite spring.  This is what I did for my cobble gen.

aa
aab
