### ISSUE TITLE
Stone barrel used as fuel?

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#107]
The stone barrel/compost bins shouldn't be usable as fuel in a furnace.

**Comment by dmillerw** [comment]
Unfortunately not such a quick fix. MC is hard-coded to allow all wooden blocks to be used as fuel...

**Comment by CyanideX** [comment]
Dang! Any way to remove it altogether?

**Comment by valsnoisytoys** [comment]
But this is the stone barrel/comost bin - not the wooden ones. There isn't wood in their construction (or there isn't in Infernal Skies 0.1.5.0).

**Comment by CyanideX** [comment]
They share the same ID as the wood ones so we can't split them.

**Comment by CyanideX** [comment]
lol, nice label. :stuck_out_tongue_winking_eye:

**Comment by tterrag1098** [comment]
Really sad that forge did not allow overriding of vanilla values. It would not be hard, I could do it in a few minutes, but it would probably be ignored :/

**Comment by dmillerw** [comment]
The last one was...

**Comment by CyanideX** [comment]
You could always... add it to Subsistence. ;)

**Comment by tterrag1098** [comment]
Yes it would be a pretty minor patch. Simply move the `GameRegistry.getFuelValue()` check to the beginning then `if (value == 0) { // do vanilla checks } else { return value; }`

Everything sounds easier in theory though
