### ISSUE TITLE
Chest Doesn't Open Under Sieve on Server

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#109]
When a chest is under a sieve on a server, the chest won't open. However, it does open when playing singleplayer.

**Comment by CyanideX** [comment]
Still having an issue on the server.

**Comment by dmillerw** [comment]
_is confused_
:(

**Comment by valsnoisytoys** [comment]
The hammer mill has this issue as well (0.1.5.1) on the server.  Will this fix for the table sieve also fix the mill?

**Comment by CyanideX** [comment]
I know @dmillerw fixed the sieve but I don't know if it applies to other blocks.
