### ISSUE TITLE
Sawdust.json is set to use sand

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/Subsistence#120]
sawdust.json is set to use sand as the input block not sawdust

**Comment by dmillerw** [comment]
Please try and use the [Infernal Skies](https://github.com/CyanideX/InfernalSkies) issue tracker for these

**Comment by valsnoisytoys** [comment]
I'm so sorry, I didn't see the note about config issues being infernal skies not subsistence issues until just now. :(  I was going to move them but I saw you're already tagging them.

**Comment by valsnoisytoys** [comment]
I can move the one's you've tagged as Infernal Skies over - don't want to double enter if you're already doing them and I just can't see  yet.

**Comment by valsnoisytoys** [comment]
Moved to Infernal Skies Repo. Sorry!
