### ISSUE TITLE
Not enough nether diamond shards from hammer mill?

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/Subsistence#123]
Is the hammer mill supposed to give more than 1 shard per nether diamond? Because its just giving 1.

**Comment by valsnoisytoys** [comment]
Moved to Infernal Skies Repo. Sorry!

**Comment by CyanideX** [comment]
Yes. Supposed to be one shard. Is this too difficult for progression?

**Comment by valsnoisytoys** [comment]
I think so, suggest 1 to 3 (range). (Comment is also on other repo).
