### ISSUE TITLE
0.1.5.1 Server: Intended? Hammer mill can 'retain' work

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/Subsistence#127]
If you keep turning the handle after the mill is empty, the next item you put in will be processed early (or immediately if you turned it long enough).  Is this intended?

**Comment by CyanideX** [comment]
Not really intended but just how it worked out (blame @tterrag1098 :wink:). We can look into changing that.

**Comment by lclc98** [comment]
Il work on fixing it now
