### ISSUE TITLE
Suggestion: allow hoppers to place items on the drying table and pull off of it

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/Subsistence#128]
I tried this on the server to see if this worked first before submitting this suggestion. Alas, it didn't.
I had the following setup:

Hopper (with rotten flesh)
Wooden Table
Grated Hopper (with leather set as allowed through)
Chest

**Comment by CyanideX** [comment]
LOL, @jaredlll08 fixed this non-issue. 😆 I didn't want tables to be automated because it makes it too easy. Tables are the stepping stones to bigger and better things.
