### ISSUE TITLE
Command for Teleporation between Overworld and Nether

### ISSUE THREAD

**Issue by Yulife** [CyanideX/Subsistence#27]
This is to ditch Mystcraft as it is a giant mod. This would be the /tpx [dimension ID] command of Mystcraft.

**Comment by CyanideX** [comment]
XComp was kind enough to make a separate TP mod. :smile:

**Comment by CyanideX** [comment]
Reopened because the teleportation command is again needed for the start of the map.

**Comment by dmillerw** [comment]
Using the default methods for moving Players cross dimensions won't work. Specifically when teleporting a Player to the Nether, a portal will be spawned.

**Comment by MattDahEpic** [comment]
I would recomend taking a look at CoFH's tpx command: https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/command/CommandTPX.java
