### ISSUE TITLE
Camo Block

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#34]
Would like a block similar to the Sky Block from OpenBlocks but, if possible, acts like camo from all directions.

**Comment by dmillerw** [comment]
What do you mean by that? An invisible block?

**Comment by CyanideX** [comment]
I wasn't sure if invisibility would be possible within Minecraft, I just wanted a block that could hide any structure behind it.

**Comment by dmillerw** [comment]
I can make something that can hide a block one layer deep, when viewed from
that side

**Comment by CyanideX** [comment]
I was hoping to hide a building. :stuck_out_tongue: So maybe a sky colored block would work best instead. Otherwise... maybe a completed sky block structure that could hide anything within it?
