### ISSUE TITLE
Compost Bin Functionality

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#46]
Basic compost functionality is similar to barrels, minus fluid collection. All types of foliage (as determined by a JSON config) can be added to the bin and over time it will decompose into dirt (length determined by config).

WOOD:
- [x]  Add items to bin, close lid, over time they decompose to dirt.

STONE:
- [x] Applying a heat source to decomposing contents will result in an output item and condensation (water).
- [x] Right click the water inside the bin with a bucket to collect it.
- [x] Right click the remaining byproduct to collect it.
- [x] If you leave the item and water inside, you can add a catalyst (determined by config) to add to it. Simply close the lid and over time you will create something new. (Example: Add leaves to compost bin, close lid, apply heat source, will turn to dirt and water, open lid, add cobweb, close lid, wait, will turn into mycelium).

**Comment by MattDahEpic** [comment]
If the lid is opened while composting, should the bin reset composting progress?

**Comment by CyanideX** [comment]
If you open the lid in real life does the composting progress reset? :stuck_out_tongue_winking_eye:
