### ISSUE TITLE
JSON Changes

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#47]
General:
- [x] Allow addition of mod items in the recipes (ie. IC2:itemPlates:7).

Sieve:
- [x] Field to determine hand sieve or table sieve recipe.
- [x] Field to determine how long the sifting will take for hand/table sieves.

Table: Drying
- [x] No need for durability field when drying.
- [x] Field to determine if an item is perishable.

**Comment by dmillerw** [comment]
You can simply omit the durability field. Isn't required
