### ISSUE TITLE
Barrel Water Recipes & Rain

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#58]
Barrels recipes should work with a fluid amount equal to or greater than the required amount. If the barrel is collecting rainwater and the recipe is initiated, all water can be consumed in turn for the resulting recipe.

Currently, barrels require an exact amount (specified by the JSON config) which conflicts when it is raining.

**Comment by dmillerw** [comment]
Recipes requiring fluid now accept an amount greater than or equal to the specified amount

The remaining fluid is lost... revisit?
