### ISSUE TITLE
Crashing with Progressive Automation

### ISSUE THREAD

**Issue by InkDragon** [CyanideX/Subsistence#66]
http://pastebin.com/KHdxk4Hw

**Comment by MattDahEpic** [comment]
This is not a problem with Subsistence. This error is related to Subsistence's dumping of all item id's to disk on launch. Some mod is registering their items/blocks as null and such a bug should be reported to them.

**Comment by dmillerw** [comment]
Lol, what you smokin' bro. NPE is clearly on the line retrieving the config setting for item dumping

**Comment by dmillerw** [comment]
Fixed in latest commit
