### ISSUE TITLE
Wooden Bucket

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#70]
Hit a roadblock with the IC2 recipes for buckets and would like to add a wooden bucket.

It should only be able to hold cold fluids (non-lava) and will have a limited use / durability.

Exmpty:
![bucket_wood](https://cloud.githubusercontent.com/assets/3106700/7922708/dd39949e-0862-11e5-9b4b-69606e010830.png)
Boiling Water:
![bucket_wood_boilingwater](https://cloud.githubusercontent.com/assets/3106700/7922709/dd3b686e-0862-11e5-8de9-f5e9055d7672.png)
Water:
![bucket_wood_water](https://cloud.githubusercontent.com/assets/3106700/7922710/dd3c341a-0862-11e5-895e-738a453d3fd3.png)

**Comment by dmillerw** [comment]
So cold fluids AND boiling water?

**Comment by CyanideX** [comment]
HEY! I wrote "non-lava" as I couldn't think of any other fluids that hot. :stuck_out_tongue: But yes, it should hold boiling water. That aint gonna set wood on fire.
