### ISSUE TITLE
Crash during initialization

### ISSUE THREAD

**Issue by ghost** [CyanideX/Subsistence#81]
http://pastebin.com/tzFqwFDf

All I know is that it has something to do with the wooden bucket. Also, sorry if this issue is already fixed.

**Comment by dmillerw** [comment]
Do you have a _main.json_ file in _Subsistence/config/_?

If so, can you post it here?

**Comment by ghost** [comment]
I do, but it's completely empty. No text whatsoever.

**Comment by ghost** [comment]
I'm not sure if this will help, but I found out that this version will only load if the configs are already generated from a previous version. I used Subsistence-1.7.10-0.0.B45 first to generate the configs and then updated to Subsistence-1.7.10-0.0.6.0, and then it worked fine in terms of loading.

Edit: Here's what's in main.json http://pastebin.com/UTU6m9hL

**Comment by ghost** [comment]
Well, it no longer crashes, so I _think_ the issue is solved
