### ISSUE TITLE
Server and Client item de-sync

### ISSUE THREAD

**Issue by Fyknown** [CyanideX/Subsistence#82]
Items become uncraftable while on a server. I don't know if it is a mod interaction or if its just the mod itself, however no one on my server including myself is capable of crafting items from the mod. Spawning them in and placing them is doable though.

**Comment by dmillerw** [comment]
Recipes are currently implemented via MineTweaker (blame @CyanideX), so the issue probably lies there

**Comment by Fyknown** [comment]
So its a possible issue between Subsistence and MineTweaker. Hopefully he moves recipes into the mod itself soon though.

**Comment by Peach774** [comment]
Shouldn't this be fixed in v1.2.0 or greater? I can craft stuff on my server.

**Comment by CyanideX** [comment]
It should be fixed now... will test again.

**Comment by CyanideX** [comment]
Was an issue with MineTweaker. Solved by converting recipes to CustomThings.
