### ISSUE TITLE
Smashing table crashes game

### ISSUE THREAD

**Issue by Fyknown** [CyanideX/Subsistence#85]
When the smashing table or table is punched with a stone it crashes the game/server and on restart it spawns a wither skeleton(?). Here's the crash log http://pastebin.com/wVcwQFwV

**Comment by dmillerw** [comment]
What the...

**Comment by Fyknown** [comment]
Just tested it, the wither skeleton diffinately spawns everytime, I dont know why...

**Comment by dmillerw** [comment]
Looks like a weird conflict with Progression. How its happening though, I don't know.

**Comment by Fyknown** [comment]
Probably should note this is on subsistence release 0.07.11

**Comment by CyanideX** [comment]
Ok WTF... I'm baffled.

**Comment by CyanideX** [comment]
Could you please tell me exactly how you're doing this, step by step with exact items?

**Comment by Fyknown** [comment]
We tested it with both a netherrind smashing table and a regular table, by holding a stone and just punching the table/smashing table, it force closes the server stating the engine has errored and upon restart and logging back in a wither skeleton has spawned in a radius of 4 blocks around the table in the southwest direction

**Comment by CyanideX** [comment]
I just tested this with my instance and server using the stone block and a rock and was unable to reproduce. What do you mean "a stone"?

**Comment by Fyknown** [comment]
Its a rock, (id:5656:43), from customthings

**Comment by CyanideX** [comment]
Yeah I'm not getting this issue. :confused:

**Comment by CyanideX** [comment]
You sure you copied over all your configs to the server from the latest update?

**Comment by Fyknown** [comment]
Its happening on my server everytime without fail, yes the configs are all the same from before the update

**Comment by CyanideX** [comment]
Well you need to update the configs on the server as well! :stuck_out_tongue_closed_eyes:

**Comment by Fyknown** [comment]
I updated the configs, and the error still occurs, i tested it in singleplayer and it doesn't happen, its only a server thing.

**Comment by CyanideX** [comment]
Are you able to place a hot iron ingot on the smashing table?

**Comment by Fyknown** [comment]
No it crashes the server as well

**Comment by CyanideX** [comment]
FIXED! Update coming within the hour.
