### ISSUE TITLE
Barrel Sapling Texture Bug

### ISSUE THREAD

**Issue by Peach774** [CyanideX/Subsistence#86]
Using bamboo saplings to fill a barrel results in a wierd texture
![2015-06-11_18 19 43](https://cloud.githubusercontent.com/assets/5171184/8121889/963e0ee2-1066-11e5-8b3e-72b30e7fb3d1.png)

**Comment by CyanideX** [comment]
This should be fixed in Subsistence 0.0.7.11. :confused:

**Comment by Peach774** [comment]
I'm running Infernal Skies 1.2.8. Playing on fast graphics if it matters.

**Comment by CyanideX** [comment]
Ah, ok. Can confirm all non-vanilla saplings display differently.

![Saplings](http://i.imgur.com/wpbgE1Y.png)
