### ISSUE TITLE
Netherrind Hardness

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#91]
Netherrind can be broken by hand.

It should be similar to cobblestone by slightly harder.

Currently, breaking it with a pick takes longer than cobblestone does, but is much quicker to break without a tool than cobble.

**Comment by dmillerw** [comment]
Unfortunately also not a quick fix necessarily, as material (which is per block) defines break-ability

**Comment by CyanideX** [comment]
This kinda needs to be done though. :disappointed: The player just breaks it by hand and it defeats the purpose of tools.

**Comment by dmillerw** [comment]
I _can_ fix it, but it would break compatibility with previous maps

**Comment by CyanideX** [comment]
I guess we will need to do that. It's _that_ important. :disappointed:

**Comment by tterrag1098** [comment]
Im pretty sure there is a way around this, I will look tomorrow.

**Comment by dmillerw** [comment]
No harm in splitting them anyway.

**Comment by tterrag1098** [comment]
Except that it will break all old worlds?

**Comment by CyanideX** [comment]
They will both exist but only the new netherrind will be generated from 
boiling
water and lava as a resource (also dmillerw did you update that?).

**Comment by dmillerw** [comment]
Yup, definitely.
Pay no attention to the fact that I just committed that change.
<_<

**Comment by dmillerw** [comment]
Also, be lucky your email woke me up ;)

**Comment by CyanideX** [comment]
LMAO. Nice coverup.
