### ISSUE TITLE
Wormwood Growth Consistency

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#92]
Wormwood seems to not grow at all in the Overworld. Could be an issue with light levels in that dimension. If possible, let's have wormwood take a specific amount of time to grow and then dry instead of random growth.

**Comment by CyanideX** [comment]
Another report of wormwood not growing at all in the overworld. Could you look into this @dmillerw?

**Comment by VikeStep** [comment]
Fixed in 3f4cc02c0c613e81d1e4b7d3ef32910d09a54762
