### ISSUE TITLE
Teleporting Between Dimensions / Relog - Models Black

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#94]
When teleporting between dimensions or relogging, all of the models appear to be black until they are right clicked at which point they render as normal.

**Comment by CyanideX** [comment]
![sample](http://i.imgur.com/XIFmSNA.png)

**Comment by dmillerw** [comment]
Can reproduce, but... I'm absolutely baffled. Lighting is a vanilla thing, even with custom models.

**Comment by CyanideX** [comment]
Like most of my other issues, they only occur on the server. I can't 
reproduce
in single player.

**Comment by dmillerw** [comment]
Same

**Comment by CyanideX** [comment]
It's very strange. Maybe the server just isn't updating the lighting as
quickly... I should test with only Subsistence.

**Comment by valsnoisytoys** [comment]
Its happening on our server as well. After death (always I think??) and (sometimes) on logging in.

**Comment by CyanideX** [comment]
I think this was already fixed. Just not released yet.

**Comment by valsnoisytoys** [comment]
Cool. 0.1.5.2 I imagine - I'll let you know if it reoccurs after that update is out.
