### ISSUE TITLE
Barrel Lid Textures Swapped

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Subsistence#96]
The stone barrel lid has the Netherrind texture and vise versa.

**Comment by dmillerw** [comment]
Could've sworn I fixed that.

WHO TOUCHED MY STUFF!?

**Comment by CyanideX** [comment]
No no, that was the actual barrels. :stuck_out_tongue_winking_eye: We just forgot to fix the lids.

**Comment by dmillerw** [comment]
Fixed in latest commit
